language: objective-c
osx_image: xcode8.3
podfile: Example/Podfile

before_install:
 - |
    gem install xcpretty -N --no-ri --no-rdoc
    gem install cocoapods
    pod install --project-directory=Example
script:
 - |
    set -o pipefail
    xcodebuild clean build -workspace Example/ISPhotoBrowser.xcworkspace -scheme ISPhotoBrowser-Example -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' | xcpretty